### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by croban** [nul800sebastiaan/Cultiv.Tabify#14]
Hi, would you provide an nuget package also soon?
br

**Comment by nul800sebastiaan** [comment]
I would love it, that will require an automated build process. I have the new GitHub Actions available on this account. I would like to do the following with it:

- Need to automatically build a package compatible with Our
- Need to automatically build a nuget package
- Need to be able to update the version number somehow 
- Would be great to be able to automatically publish the NuGet package when a tag gets added to a commit (release tag)

I know this is all possible since Warren has been working on experiments around this recently. Just need to figure out how exactly we can make it all fit together. Fun project!

**Comment by ronaldbarendse** [comment]
The automatic versioning could be done using [GitVersion](https://github.com/GitTools/GitVersion): install the [MSBuild task](https://gitversion.readthedocs.io/en/latest/usage/msbuild-task/) and optionally [configure](https://gitversion.readthedocs.io/en/latest/configuration/) it (if you're using GitFlow, it should already generate the correct version numbers).

Generating the NuGet package is also quite easy if you use the new SDK-style project format: https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package-msbuild.

**Comment by nul800sebastiaan** [comment]
Thanks for reporting this! I have just retired this package since there's something better out there! 👍

Mister Søren Kottal has made many improvements on this package and it's time for me to retire this one! 🎉 If this is still an issue then make sure to head over to https://github.com/skttl/our-umbraco-matryoshka instead.
