### ISSUE TITLE
FF issue: Some tabs are inaccessible in narrow screen views or in doc types with lots of tabs

### ISSUE THREAD

**Issue by ZacP** [nul800sebastiaan/Cultiv.Tabify#16]
If there are more tabs than can fit in the displayable view, those tabs are inaccessible in FireFox.  In Chrome, the tabs wrap to the next line.  Here's an example of the tabs on a wide screen view and a narrow view.  Note the "Page Settings" tab doesn't display on the narrow view.

**Wide view**
![image](https://user-images.githubusercontent.com/5231911/67045506-a9e74e80-f0eb-11e9-81c1-a0021a93c4b5.png)

**Narrow view in FireFox**
![image](https://user-images.githubusercontent.com/5231911/67045537-b8356a80-f0eb-11e9-9da1-d4b5eec76540.png)

**Narrow view Chrome** 
![image](https://user-images.githubusercontent.com/5231911/67045793-34c84900-f0ec-11e9-9650-76ea77fa67f2.png)

In Umbraco 8.2 with the latest Cultiv.Tabify package.  Works fine in Chrome, doesn't work in FireFox 69.0.3 on Windows 10.

**Comment by nul800sebastiaan** [comment]
Thanks @ZacP - if you know how to fix it then I'd love to see a PR!

**Comment by nul800sebastiaan** [comment]
Thanks for reporting this! I have just retired this package since there's something better out there! 👍

Mister Søren Kottal has made many improvements on this package and it's time for me to retire this one! 🎉 If this is still an issue then make sure to head over to https://github.com/skttl/our-umbraco-matryoshka instead.
