### ISSUE TITLE
Rich text editor toolbar not visible

### ISSUE THREAD

**Issue by AndyVokurka** [nul800sebastiaan/Cultiv.Tabify#19]
Hello. When using Rich text editor with lots of text inside of grid (so that I have to scroll down) the RTE toolbar gets hidden below the "Reorder" button.

**Comment by nul800sebastiaan** [comment]
Thanks for reporting this! I have just retired this package since there's something better out there! 👍

Mister Søren Kottal has made many improvements on this package and it's time for me to retire this one! 🎉 If this is still an issue then make sure to head over to https://github.com/skttl/our-umbraco-matryoshka instead.
